### ISSUE TITLE
Use secrets instead of helm parameters

### ISSUE THREAD

**Issue by cep21** [larderdev/kubewise#13]
When you run `kubectl get pod -o yaml XYZ` you see all the environment variables of the pod.  It is better to keep them inside secrets, for things like slack tokens.  Here is what I did to my deployment.yaml file.

```
            - name: KW_SLACK_TOKEN
              valueFrom:
                secretKeyRef:
                  name: kubewise
                  key: slack-token
```

An alternative is to use `envFrom` in k8s and inject into ENV all the keys of a secret.  Either work, but maybe standardizing on the existence of a secret kubewise is reasonable.
